export const CartActionTypes = {
    TYPE_TOGGLE_CART_HIDDEN: 'TYPE_TOGGLE_CART_HIDDEN',
    TYPE_ADD_ITEM: 'TYPE_ADD_ITEM',
    TYPE_REMOVE_ITEM_FROM_CART: 'TYPE_REMOVE_ITEM_FROM_CART',
    TYPE_INCREASE_ITEM_QUANTITY: 'TYPE_INCREASE_ITEM_QUANTITY',
    DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY'
}